from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.base import get_db
from app.api.bcos import list_bcos
from typing import Dict, Any, List

router = APIRouter(prefix="/mcp", tags=["mcp"])

@router.get("/resources")
async def list_resources():
    """MCP standard for listing available resources."""
    return {
        "resources": [
            {
                "uri": "cortex://bcos",
                "name": "Behavioral Context Objects",
                "description": "Durable semantic context about organizational behavior",
                "mimeType": "application/json"
            }
        ]
    }

@router.get("/tools")
async def list_tools():
    """MCP standard for listing available tools for agents."""
    return {
        "tools": [
            {
                "name": "query_context",
                "description": "Retrieve relevant behavioral context for a user or team",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "user_id": {"type": "string"},
                        "scope": {"type": "string", "enum": ["individual", "team", "organization"]}
                    },
                    "required": ["query"]
                }
            },
            {
                "name": "share_agent_context",
                "description": "Publish context discovered or generated by an agent back to the CORTEX substrate",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "label": {"type": "string"},
                        "observations": {"type": "array", "items": {"type": "string"}},
                        "confidence": {"type": "number"},
                        "agent_id": {"type": "string"}
                    },
                    "required": ["label", "observations"]
                }
            }
        ]
    }

@router.post("/tools/query_context")
async def query_context(
    params: Dict[str, Any],
    db: AsyncSession = Depends(get_db)
):
    # This would call the VectorStore and then retrieve full BCOs from the DB
    # For now, we reuse the existing BCO listing logic
    return await list_bcos(db=db)

@router.post("/tools/share_agent_context")
async def share_agent_context(
    params: Dict[str, Any],
    db: AsyncSession = Depends(get_db)
):
    """
    Allows an external agent to contribute its own semantic observations to the CORTEX store.
    This implements the 'Agent-to-Agent Context Sharing' requirements of Phase 3.
    """
    from app.models.bco import BCOModel
    from app.schemas.bco import BCOScope, BCOType
    from datetime import datetime

    bco = BCOModel(
        scope=BCOScope.ORGANIZATION,
        scope_id="agent_contributed",
        type=BCOType.WORKFLOW_PATTERN,
        label=params["label"],
        evidence=params["observations"],
        confidence=params.get("confidence", 0.7),
        temporal_json={
            "first_observed": datetime.utcnow().isoformat(),
            "last_validated": datetime.utcnow().isoformat(),
            "validity_window": "P24H",
            "drift_flag": False
        },
        context_json={
            "domain": "agent_discovery",
            "conditions": [f"Contributed by agent: {params.get('agent_id', 'unknown')}"],
            "exceptions": []
        },
        version="1.0.0",
        lineage=[]
    )
    db.add(bco)
    await db.commit()
    return {"status": "accepted", "bco_id": bco.id}
